name: Android CI

on: [push]

jobs:
  build:

    runs-on: bitriseio/android-ndk:latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        ./gradlew androidDependencies
        ./gradlew clean assembleRelease
      env:
        JVM_OPTS: -Xmx3200m
